# Generated by Django 4.2.4 on 2024-01-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
