# Generated by Django 4.2.4 on 2024-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_employee_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='media/employee_images'),
        ),
    ]
