# Generated by Django 4.2.4 on 2024-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_leavetype_leave_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.ImageField(default='', null=True, upload_to='media/employee_images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='educational_certificates',
            field=models.ImageField(default='', null=True, upload_to='media/employee_images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_letter',
            field=models.ImageField(default='', null=True, upload_to='media/employee_images'),
        ),
    ]
