# Generated by Django 4.2.4 on 2024-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_employee_education_employee_educational_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='in_out',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
