# Generated by Django 4.2.4 on 2024-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_employee_is_manager_employee_is_user_delete_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.ImageField(default='', null=True, upload_to='employee_images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educational_certificates',
            field=models.ImageField(default='', null=True, upload_to='employee_images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience_letter',
            field=models.ImageField(default='', null=True, upload_to='employee_images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='employee_images'),
        ),
    ]
