# Generated by Django 4.2.4 on 2024-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employee_email_alter_employee_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
