# Generated by Django 4.2.4 on 2024-01-11 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0020_role_remove_employee_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='report_to',
            field=models.ManyToManyField(blank=True, related_name='employees_reported_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
