# Generated by Django 4.2.4 on 2024-01-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_employee_report_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='report_to',
        ),
    ]
