# Generated by Django 4.2.4 on 2024-01-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_remove_employee_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed', to='hrms.employee'),
        ),
    ]
