# Generated by Django 4.2.4 on 2024-01-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_employee_line_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_allowance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
    ]
